# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - transactionbootcamp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_631cd5d32e074f47b13a45dbf8ff9250 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ce5a9f0e46de46b8be4b2410b17fb11b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_631cd5d32e074f47b13a45dbf8ff9250 }}/jhctdev/transaction-service:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'transactionbootcamp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c7d2d823fdc947bea0e27c8d568558c4 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_631cd5d32e074f47b13a45dbf8ff9250 }}/jhctdev/transaction-service:${{ github.sha }}'